import type { CategoryItem, DailyLog, HistoryEntry, TaskItem } from '../../db/types'
import { calculateCategoryBreakdown } from '../study/studyDashboard'

export interface WeeklyReportData {
  studyMinutes: number
  breakMinutes: number
  goalHitDays: number
  totalDays: number
  topCategory: string
  tasksCompleted: number
  cardsReviewed: number
}

export function buildWeeklyReportData(
  history: HistoryEntry[],
  logs: DailyLog[],
  tasks: TaskItem[],
  categories: CategoryItem[],
  dailyGoalMinutes: number,
  now = new Date(),
): WeeklyReportData {
  const weekAgo = now.getTime() - 7 * 86400000
  const weekHistory = history.filter(h => h.createdAt >= weekAgo)
  const weekLogs = logs.filter(l => {
    const t = new Date(l.dateString).getTime()
    return t >= weekAgo - 86400000
  })

  const studyMinutes = weekHistory.filter(h => h.type === 'study').reduce((s, h) => s + h.durationMinutes, 0)
  const breakMinutes = weekHistory.filter(h => h.type === 'break').reduce((s, h) => s + h.durationMinutes, 0)
  const goalHitDays = weekLogs.filter(l => l.studyMinutes >= dailyGoalMinutes).length
  const { breakdown } = calculateCategoryBreakdown(weekHistory, categories)
  const topCategory = breakdown[0]?.name ?? 'None'
  const tasksCompleted = tasks.filter(t => t.completed && (t.lastCompletedAt ?? t.createdAt) >= weekAgo).length
  const cardsReviewed = weekHistory.filter(h => h.type === 'study' && h.sessionNotes?.includes('card')).length

  return {
    studyMinutes,
    breakMinutes,
    goalHitDays,
    totalDays: 7,
    topCategory,
    tasksCompleted,
    cardsReviewed,
  }
}

export function weeklyReportToMarkdown(data: WeeklyReportData, rangeLabel = 'Last 7 days'): string {
  return [
    `# Study Weekly Report`,
    ``,
    `**Period:** ${rangeLabel}`,
    ``,
    `- Study time: **${Math.round(data.studyMinutes / 60 * 10) / 10}h** (${data.studyMinutes} min)`,
    `- Break time: **${data.breakMinutes} min**`,
    `- Daily goal hit: **${data.goalHitDays}/${data.totalDays}** days`,
    `- Top category: **${data.topCategory}**`,
    `- Tasks completed: **${data.tasksCompleted}**`,
    ``,
    `_Generated by Study Dashboard_`,
  ].join('\n')
}

export function weeklyReportToCsv(data: WeeklyReportData): string {
  return [
    'metric,value',
    `study_minutes,${data.studyMinutes}`,
    `break_minutes,${data.breakMinutes}`,
    `goal_hit_days,${data.goalHitDays}`,
    `top_category,"${data.topCategory.replace(/"/g, '""')}"`,
    `tasks_completed,${data.tasksCompleted}`,
  ].join('\n')
}

export function downloadWeeklyReport(content: string, ext: 'md' | 'csv'): void {
  const blob = new Blob([content], { type: ext === 'md' ? 'text/markdown' : 'text/csv' })
  const url = URL.createObjectURL(blob)
  const a = document.createElement('a')
  a.href = url
  a.download = `weekly-report-${new Date().toISOString().slice(0, 10)}.${ext}`
  a.click()
  URL.revokeObjectURL(url)
}
